OBJS= example_processutility_hook_plugin.o
MODULE_big = example_processutility_hook
DOCS = README.example_processutility_hook
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
