#!/bin/bash

set -e -u -o pipefail

function usage() {
  echo "Usage: meta -k target|targetmeta|tsdb|walreplay|config|flags|runtime"
  exit 1
}

# what to fetch
meta=
while getopts "m:h" opt; do
  case ${opt} in
    m)
      meta=$OPTARG
      ;;
    \?|h|: )
      usage
      ;;
  esac
done

if [ -z "${meta}" ]; then
  usage
fi

function apiQuery() {
  local endpoint
  endpoint=$1
  shift
  curl -sL --socks5-hostname localhost:1081 -G "${@}" 'http://prometheus-k8s.monitoring.svc.cluster.local:9090/'"${endpoint}"  | yq --prettyPrint .
}

case "${meta}" in
  target)
    apiQuery "/api/v1/targets" --data 'scrapePool=podMonitor/monitoring/promtorture/0'
    ;;
  targetmeta)
    apiQuery "/api/v1/targets/metadata" --data 'match_target={job="monitoring/promtorture"}'
    ;;
  tsdb)
    apiQuery "/api/v1/status/tsdb"
    ;;
  walreplay)
    apiQuery "/api/v1/status/walreplay"
    ;;
  config)
    apiQuery "/api/v1/status/config"
    ;;
  flags)
    apiQuery "/api/v1/status/flags"
    ;;
  runtime)
    apiQuery "/api/v1/status/runtimeinfo"
    ;;
  *)
    echo 1>&2 "Unrecognised option: ${meta}"
    usage
    ;;
esac

# vim: set ft=sh et ai sw=2 ts=2 sts=2:
