version: "3.9"
services:
  server:
    build: .
    networks:
      - unstable
    entrypoint: /usr/local/bin/server
    cap_add:
      - NET_ADMIN
  client:
    build: .
    networks:
      - unstable
    entrypoint: /usr/local/bin/client
    cap_add:
      - NET_ADMIN
networks:
  unstable:
    name: unstable
    driver: bridge
