# Run with: docker-compose up
#
# If using SELinux, requires
#    setsebool -P container_manage_cgroup true
#
version: "3.8"
services:
  kaseya:
    # Runs the COMMAND in the Dockerfile, so not set here
    container_name: kaseya
    build:
      context: .
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 100M
    stop_signal: RTMIN+3
    cap_add:
      - CAP_SYS_ADMIN
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: false
      - type: bind
        source: /sys/fs/selinux
        target: /sys/fs/selinux
        read_only: true
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/lock
      - type: tmpfs
        target: /sys/fs/cgroup/systemd
      - type: volume
        target: /var/lib/journal
    environment:
      oci-systemd-hook: disabled
