{
 "title": "Promtorture",
 "description": "Abuse of prometheus for fun and profit",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Prometheus memory",
   "type": "timeseries",
   "description": "Prom memory stats",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}[2m])",
     "legendFormat": "max go_memstats_alloc_bytes[2m]"
    },
    {
     "expr": "max_over_time(go_memstats_heap_sys_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}[2m])",
     "legendFormat": "max go_memstats_heap_sys_bytes[2m]"
    },
    {
     "expr": "max_over_time(go_memstats_sys_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}[2m])",
     "legendFormat": "max go_memstats_sys_bytes[2m]"
    },
    {
     "expr": "max_over_time(go_memstats_heap_inuse_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}[2m])",
     "legendFormat": "max go_memstats_heap_inuse_bytes[2m]"
    },
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "prometheus_tsdb_symbol_table_size_bytes"
    },
    {
     "expr": "container_memory_working_set_bytes{container=\"prometheus\",pod=\"prometheus-k8s-0\"}",
     "legendFormat": "container_memory_working_set_bytes"
    },
    {
     "expr": "sum by () (prometheus_target_metadata_cache_bytes{job=\"prometheus-k8s\",container=\"prometheus\"})",
     "legendFormat": "sum(prometheus_target_metadata_cache_bytes)"
    },
    {
     "expr": "go_gc_gomemlimit_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "go_gc_gomemlimit_bytes"
    }
   ]
  },
  {
   "title": "TSDB head series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_created_total{job=\"prometheus-k8s\",container=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks_storage_size_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{job=\"prometheus-k8s\",container=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promtorture Scrapes",
   "type": "timeseries",
   "description": "Info on promtorture scrape results",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"monitoring/promtorture\",container=\"promtorture\"}\n*  on (job,container,pod) group_left(gauge_metrics,info_labels,targets)\n(promtorture_info{job=\"monitoring/promtorture\",container=\"promtorture\"})",
     "legendFormat": "scrape_duration_seconds: targets={{targets}} info_labels={{info_labels}} gauge_metrics={{gauge_metrics}}"
    },
    {
     "expr": "scrape_samples_scraped{job=\"monitoring/promtorture\",container=\"promtorture\"}\n*  on (job,container,pod) group_left(gauge_metrics,info_labels,targets)\n(promtorture_info{job=\"monitoring/promtorture\",container=\"promtorture\"})",
     "legendFormat": "scrape_samples_scraped: targets={{targets}} info_labels={{info_labels}} gauge_metrics={{gauge_metrics}}"
    },
    {
     "expr": "sum_over_time(scrape_series_added{job=\"monitoring/promtorture\",container=\"promtorture\"}[5m])\n*  on (job,container,pod) group_left(gauge_metrics,info_labels,targets)\n(promtorture_info{job=\"monitoring/promtorture\",container=\"promtorture\"})",
     "legendFormat": "Series added over 5min: metrics targets={{targets}} info_labels={{info_labels}} gauge_metrics={{gauge_metrics}}"
    }
   ]
  },
  {
   "title": "TSDB head chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "delta(prometheus_tsdb_head_chunks{job=\"prometheus-k8s\",container=\"prometheus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}